// Generated by vv-agent. This file is self-contained.
export type RequestId = string | number;
export type JsonValue = null | boolean | number | string | JsonValue[] | JsonObject;
export type JsonObject = { [key: string]: JsonValue };
export type ApprovalDecision = "allow" | "allow_session" | "deny" | "timeout";
export type ThreadStatus = "idle" | "running" | "archived" | "closed";
export type TurnStatus = "queued" | "running" | "completed" | "failed" | "interrupted";
export type AppItemStatus = "started" | "inProgress" | "completed" | "failed";

export interface ClientInfo { name: string; title?: string; version?: string; }
export interface ClientCapabilities { experimentalApi?: boolean; optOutNotificationMethods?: string[]; }
export interface ServerCapabilities {
  modelList: boolean; threadLifecycle: boolean; notificationOptOut: boolean;
  schemaExport: boolean; approvalResolve: boolean;
}
export interface InitializeParams { clientInfo: ClientInfo; capabilities?: ClientCapabilities; }
export interface ModelListParams { agentKey?: string; provider?: string; }
export interface ThreadStartParams { agentKey?: string; cwd?: string; metadata?: JsonObject; }
export interface ThreadIdParams { threadId: string; }
export interface ThreadResumeParams { threadId: string; subscribe?: boolean; }
export interface ThreadReadParams { threadId: string; afterItemId?: string; }
export interface ThreadListParams {
  includeArchived?: boolean; archived?: boolean; offset?: number; limit?: number;
}
export type InputItem = JsonObject;
export interface TurnStartParams { threadId: string; input?: InputItem[]; metadata?: JsonObject; }
export interface TurnSteerParams { threadId: string; expectedTurnId?: string; input?: InputItem[]; }
export interface TurnFollowUpParams { threadId: string; expectedTurnId?: string; input?: InputItem[]; }
export interface TurnInterruptParams { threadId: string; expectedTurnId?: string; reason?: string; }
export interface ApprovalRequestParams {
  requestId: string; threadId: string; turnId: string; toolCallId: string;
  toolName: string; preview: string; arguments: JsonObject;
}
export interface ApprovalResolveParams {
  requestId: string; threadId: string; turnId: string; decision: ApprovalDecision;
  reason?: string; metadata?: JsonObject;
}

export interface AppItem {
  itemId: string; threadId: string; turnId: string; type: string; status: AppItemStatus;
  payload: JsonObject; createdAt: number; updatedAt: number;
}
export interface AppThread {
  threadId: string; agentKey: string; cwd: string | null; createdAt: number; updatedAt: number;
  archivedAt: number | null; status: ThreadStatus; metadata: JsonObject;
}
export interface AppTurn {
  turnId: string; threadId: string; runId: string | null; status: TurnStatus;
  startedAt: number; completedAt: number | null; input: InputItem[]; result: JsonObject;
}
export interface ToolCallDeltaParams extends AppItem { delta: JsonValue; }
export interface WarningParams { message: string; code?: string; }
export interface InitializeResponse { userAgent: string; protocolVersion: "v1"; capabilities: ServerCapabilities; }
export interface ModelSummary {
  id: string; provider?: string; displayName?: string; contextLength?: number;
  supportsTools: boolean; metadata?: JsonObject;
}
export interface ModelListResponse { models: ModelSummary[]; }
export interface ThreadStartResponse { threadId: string; agentKey: string; cwd: string | null; status: ThreadStatus; }
export interface ThreadReadResponse { thread: AppThread; turns: AppTurn[]; items: AppItem[]; }
export interface ThreadResumeResponse { thread: AppThread; turns: AppTurn[]; items: AppItem[]; }
export interface ThreadListResponse { threads: AppThread[]; }
export interface ThreadArchiveResponse { threadId: string; archived: boolean; }
export interface ThreadUnsubscribeResponse { threadId: string; subscribed: boolean; closed: boolean; }
export interface TurnStartResponse { threadId: string; turnId: string; status: TurnStatus; }
export interface TurnQueueResponse { threadId: string; turnId: string; queued: boolean; }
export interface TurnInterruptResponse { threadId: string; turnId: string; cancelled: boolean; }
export interface ThreadStatusChangedParams { threadId: string; status: ThreadStatus; }
export interface ThreadClosedParams { threadId: string; }
export interface TurnStartedParams { threadId: string; turnId: string; }
export interface TurnCompletedParams {
  threadId: string; turnId: string; runId?: string; status: TurnStatus; finalOutput?: JsonValue;
  completionReason?: string; completionToolName?: string; partialOutput?: string;
  tokenUsage?: JsonObject; error?: string;
}
export type ApprovalResolveResponse = Record<string, never>;
export interface SchemaExportResponse { jsonSchema: Record<string, string>; typescript: Record<string, string>; }

export type ClientRequest =
  | { jsonrpc: "2.0"; id: RequestId; method: "initialize"; params: InitializeParams }
  | { jsonrpc: "2.0"; method: "initialized" }
  | { jsonrpc: "2.0"; id: RequestId; method: "model/list"; params?: ModelListParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "thread/start"; params?: ThreadStartParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "thread/resume"; params: ThreadResumeParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "thread/read"; params: ThreadReadParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "thread/archive" | "thread/unsubscribe"; params: ThreadIdParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "thread/list"; params?: ThreadListParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "turn/start"; params: TurnStartParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "turn/steer"; params: TurnSteerParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "turn/followUp"; params: TurnFollowUpParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "turn/interrupt"; params: TurnInterruptParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "approval/resolve"; params: ApprovalResolveParams }
  | { jsonrpc: "2.0"; id: RequestId; method: "schema/export"; params?: Record<string, never> };

export type ServerNotification =
  | { jsonrpc: "2.0"; method: "thread/started"; params: ThreadStartResponse }
  | { jsonrpc: "2.0"; method: "thread/status/changed"; params: ThreadStatusChangedParams }
  | { jsonrpc: "2.0"; method: "thread/archived"; params: ThreadArchiveResponse }
  | { jsonrpc: "2.0"; method: "thread/closed"; params: ThreadClosedParams }
  | { jsonrpc: "2.0"; method: "turn/started"; params: TurnStartedParams }
  | { jsonrpc: "2.0"; method: "turn/completed"; params: TurnCompletedParams }
  | { jsonrpc: "2.0"; method: "item/started" | "item/completed"; params: AppItem }
  | { jsonrpc: "2.0"; method: "item/agentMessage/delta"; params: AppItem & { delta: string } }
  | { jsonrpc: "2.0"; method: "item/toolCall/delta"; params: ToolCallDeltaParams }
  | { jsonrpc: "2.0"; method: "approval/requested"; params: ApprovalRequestParams }
  | { jsonrpc: "2.0"; method: "approval/resolved"; params: ApprovalResolveParams }
  | { jsonrpc: "2.0"; method: "error/warning"; params: WarningParams };

export type ServerRequest = {
  jsonrpc: "2.0"; id: RequestId; method: "approval/request"; params: ApprovalRequestParams;
};
export type ClientResult =
  | InitializeResponse | ModelListResponse | ThreadStartResponse | ThreadReadResponse
  | ThreadResumeResponse | ThreadListResponse | ThreadArchiveResponse | ThreadUnsubscribeResponse
  | TurnStartResponse | TurnQueueResponse | TurnInterruptResponse | ApprovalResolveResponse
  | SchemaExportResponse;
export type JsonRpcSuccess = { jsonrpc: "2.0"; id: RequestId; result: ClientResult | JsonValue };
export type JsonRpcError = {
  jsonrpc: "2.0"; id: RequestId | null;
  error: { code: number; message: string; data?: JsonValue };
};
export type JsonRpcMessage = ClientRequest | ServerNotification | ServerRequest | JsonRpcSuccess | JsonRpcError;
